# Generated by Django 2.2.28 on 2023-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sdft'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdft',
            name='sdsfw',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdft',
            name='xvvss',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
