# Generated by Django 2.2.28 on 2023-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hncnc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hncnc',
        ),
        migrations.AddField(
            model_name='sdft',
            name='cbcbx',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
